require 'json'
require 'net/https'

module BrowserID
  module Verifier
    # Public: This class sends the assertion to Mozilla's Persona server for
    # verification.
    class Persona
      attr_accessor :server, :path, :audience

      # Public: String defining the endpoint of the server to perform Persona
      # verifications against.
      VERIFICATION_SERVER = 'verifier.login.persona.org'

      # Public: String defining the normal path to POST assertion verifications
      # to.
      VERIFICATION_PATH = '/verify'

      # Public: Constructs a new Persona verifier.
      #
      # audience - The BrowserID audience. This should be a URI String with the
      #            scheme and authority sections for the serve to authenticate
      #            the client against.
      #
      # Examples
      #
      #   BrowserID::Verifier::Persona.new("https://example.com:443")
      #
      def initialize(audience)
        @server = VERIFICATION_SERVER
        @path = VERIFICATION_PATH
        @audience = audience
      end

      # Public: Verifies a Persona assertion for a given audience.
      #
      # assertion - Persona authentication assertion generated by the login frame.
      #
      # Returns the authenticated email address String if the assertion is valid.
      # Raises an exception with a failure message if the client was not
      # successfully authenticated.
      #
      # Examples
      #
      #   verify(assertion)
      #   # => "user@example.com"
      #
      def verify(assertion)
        http = Net::HTTP.new(VERIFICATION_SERVER, 443)
        http.use_ssl = true

        verification = Net::HTTP::Post.new('/verify')
        verification.set_form_data(assertion: assertion, audience: @audience)

        response = http.request(verification)
        raise "Unsuccessful response from #{@server}: #{response}" unless response.kind_of? Net::HTTPSuccess
        authentication = JSON.parse(response.body)

        # Authentication response is a JSON hash which must contain a 'status'
        # of "okay" or "failure".
        status = authentication['status']
        raise "Unknown authentication status '#{status}'" unless %w{okay failure}.include? status

        # An unsuccessful authentication response should contain a reason string.
        raise "Unsuccessful persona assertion: #{authentication['reason']}" unless status == "okay"

        # A successful response looks like the following:
        # {
        #   "status": "okay",
        #   "email": "user@example.com",
        #   "audience": "https://service.example.com:443",
        #   "expires": 1234567890,
        #   "issuer": "persona.mozilla.com"
        # }

        audience = authentication['audience']
        raise "Persona assertion audience '#{audience}' does not match verifier audience #{@audience}" unless audience == @audience

        expires = authentication['expires'] && Time.at(authentication['expires'].to_i/1000.0)
        raise "Persona assertion expired at #{expires}" if expires < Time.now

        authentication['email']
      end
    end
  end
end
